name: decision-flowformer-gym
channels:
- pytorch
dependencies:
- python=3.8.5
- anaconda
- cudatoolkit=10.
- numpy
- pip
- pip:
  - gym==0.18.3
  - mujoco-py==2.0.2.13
  - numpy==1.20.3
  - torch==1.8.1
  - transformers==4.5.1
  - wandb==0.9.1
  - coolname==1.1.0
  - termcolor==1.1.0
  - tensorboard==2.7.0
  - protobuf==3.17.3


